---
- name: SSH config
  hosts: pikvm
  become: yes
  gather_facts: yes

  vars:
  
    # Disallow password authentication
    sshd_password_authentification: 'no'

  tasks:

    - name: Mount host filesystem read/write
      # See: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/raw_module.html
      raw: rw
      changed_when: False
      register: result
      failed_when:
      - result.rc != 0

    - name: Include the ssh_hardening role
      include_role:
        name: diodonfrost.ssh_hardening

    - name: Mount host filesystem read-only
      # See: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/raw_module.html
      raw: ro
      changed_when: False
      register: result
      failed_when:
      - result.rc != 0